In [791]:
x_test=pd.read_excel("test_agriculture.xlsx")
x_train=pd.read_excel("train_agriculture.xlsx")

In [792]:
x_test=x_test.drop(columns=["ID"])
x_train=x_train.drop(columns=["ID"])

In [793]:
df = pd.concat([x_test, x_train])

In [794]:
import pandas as pd
import numpy as np
#df=pd.read_excel("test_agriculture.xlsx")
df

Estimated_Insects_Count  Crop_Type  Soil_Type  Pesticide_Use_Category  \
0                         188          1          1                       1   
1                         410          1          1                       1   
2                         626          1          0                       1   
3                         731          1          0                       1   
4                         789          0          0                       1   
...                       ...        ...        ...                     ...   
4594                     2138          0          1                       2   
4595                     2139          0          1                       2   
4596                     2267          0          1                       2   
4597                     2267          0          1                       2   
4598                     2267          0          1                       2   

      Number_Doses_Week  Number_Weeks_Used  Number_Weeks_Quit  Season  \
0                     0                NaN                  0       2   
1                     0                0.0                  0       2   
2                     0                0.0                  0       2   
3                     0                0.0                  0       2   
4                     0                0.0                  0       1   
...                 ...                ...                ...     ...   
4594                 20                NaN                  1       1   
4595                 30               47.0                  2       1   
4596                 10                7.0                 27       2   
4597                 10               20.0                 24       2   
4598                 10               33.0                 17       2   

      Crop_Damage  
0             NaN  
1             NaN  
2             NaN  
3             NaN  
4             NaN  
...           ...  
4594          1.0  
4595          1.0  
4596          0.0  
4597          0.0  
4598          0.0  

[5798 rows x 9 columns]

In [795]:
df.shape

(5798, 9)

In [796]:
df.isnull().sum()

Estimated_Insects_Count       0
Crop_Type                     0
Soil_Type                     0
Pesticide_Use_Category        0
Number_Doses_Week             0
Number_Weeks_Used           561
Number_Weeks_Quit             0
Season                        0
Crop_Damage                1199
dtype: int64

In [797]:
df.dtypes

Estimated_Insects_Count      int64
Crop_Type                    int64
Soil_Type                    int64
Pesticide_Use_Category       int64
Number_Doses_Week            int64
Number_Weeks_Used          float64
Number_Weeks_Quit            int64
Season                       int64
Crop_Damage                float64
dtype: object

In [798]:
df.dropna(inplace=True)

In [ ]:
sns.barplot(x="Number_Weeks_Used",y="Crop_Damage",data=df)

In [ ]:
sns.barplot(x="Estimated_Insects_Count",y="Crop_Damage",data=df)

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt
sns.pairplot(df)
plt.show()

In [800]:
df.describe(include='all')

Estimated_Insects_Count    Crop_Type    Soil_Type  \
count              4157.000000  4157.000000  4157.000000   
mean               1368.286264     0.225403     0.475343   
std                 815.550890     0.417898     0.499452   
min                 150.000000     0.000000     0.000000   
25%                 732.000000     0.000000     0.000000   
50%                1212.000000     0.000000     0.000000   
75%                1898.000000     0.000000     1.000000   
max                4097.000000     1.000000     1.000000   

       Pesticide_Use_Category  Number_Doses_Week  Number_Weeks_Used  \
count             4157.000000        4157.000000        4157.000000   
mean                 2.282175          26.528747          28.891027   
std                  0.471010          15.651629          12.586005   
min                  1.000000           0.000000           0.000000   
25%                  2.000000          15.000000          20.000000   
50%                  2.000000          20.000000          28.000000   
75%                  3.000000          40.000000          38.000000   
max                  3.000000          95.000000          66.000000   

       Number_Weeks_Quit       Season  Crop_Damage  
count        4157.000000  4157.000000  4157.000000  
mean            9.293481     1.891989     0.191484  
std             9.753605     0.696910     0.452663  
min             0.000000     1.000000     0.000000  
25%             0.000000     1.000000     0.000000  
50%             7.000000     2.000000     0.000000  
75%            16.000000     2.000000     0.000000  
max            47.000000     3.000000     2.000000

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt  
corr = df.corr()
plt.subplots(figsize=(15,10))
sns.heatmap(corr, xticklabels=corr.columns, yticklabels=corr.columns, annot=True, cmap=sns.diverging_palette(220, 20, as_cmap=True))

In [801]:
df.corr()

Estimated_Insects_Count  Crop_Type  Soil_Type  \
Estimated_Insects_Count                 1.000000  -0.039040  -0.156353   
Crop_Type                              -0.039040   1.000000  -0.174532   
Soil_Type                              -0.156353  -0.174532   1.000000   
Pesticide_Use_Category                 -0.035732   0.355242   0.020889   
Number_Doses_Week                      -0.124894  -0.165631   0.051378   
Number_Weeks_Used                       0.449470  -0.002237  -0.098399   
Number_Weeks_Quit                       0.249871  -0.272315  -0.037584   
Season                                 -0.015429   0.001822   0.003753   
Crop_Damage                             0.196067   0.027448  -0.057868   

                         Pesticide_Use_Category  Number_Doses_Week  \
Estimated_Insects_Count               -0.035732          -0.124894   
Crop_Type                              0.355242          -0.165631   
Soil_Type                              0.020889           0.051378   
Pesticide_Use_Category                 1.000000          -0.007122   
Number_Doses_Week                     -0.007122           1.000000   
Number_Weeks_Used                      0.387982           0.104022   
Number_Weeks_Quit                     -0.570960          -0.032430   
Season                                 0.010773          -0.006366   
Crop_Damage                            0.202449          -0.017724   

                         Number_Weeks_Used  Number_Weeks_Quit    Season  \
Estimated_Insects_Count           0.449470           0.249871 -0.015429   
Crop_Type                        -0.002237          -0.272315  0.001822   
Soil_Type                        -0.098399          -0.037584  0.003753   
Pesticide_Use_Category            0.387982          -0.570960  0.010773   
Number_Doses_Week                 0.104022          -0.032430 -0.006366   
Number_Weeks_Used                 1.000000          -0.467386 -0.011108   
Number_Weeks_Quit                -0.467386           1.000000  0.002753   
Season                           -0.011108           0.002753  1.000000   
Crop_Damage                       0.244988          -0.155354 -0.016798   

                         Crop_Damage  
Estimated_Insects_Count     0.196067  
Crop_Type                   0.027448  
Soil_Type                  -0.057868  
Pesticide_Use_Category      0.202449  
Number_Doses_Week          -0.017724  
Number_Weeks_Used           0.244988  
Number_Weeks_Quit          -0.155354  
Season                     -0.016798  
Crop_Damage                 1.000000

In [730]:
#from sklearn.impute import SimpleImputer 
#imp=SimpleImputer(missing_values=np.nan,strategy='mean')
#df['Number_Weeks_Quit']=imp.fit_transform(df['Number_Weeks_Quit'].values.reshape(-1,1))

In [ ]:
#chexking skewness
df.skew

In [803]:
skew=df.columns
for col in skew:
    if df.skew().loc[col]>0.55:
        df[col]=np.log1p(df[col])

In [804]:
from scipy.stats import zscore
z_score=abs(zscore(df))
df_final= df.loc[(z_score<3).all(axis=1)]
print(df_final.shape)

(3995, 9)


In [805]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
list1=['Crop_Damage','Number_Weeks_Used','Estimated_Insects_Count']
for val in list1:
    df[val]=le.fit_transform(df[val].astype(str))

In [806]:
#saperate input and target variabke
import numpy as np
y=df["Crop_Damage"]
df_x=df.drop(columns=["Crop_Damage"])
print(df_x.shape)
print(y.shape)


(4157, 8)
(4157,)


In [807]:
# prediction with region
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,roc_auc_score,roc_curve
from sklearn.ensemble import AdaBoostClassifier,GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [809]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
target = df['Crop_Damage']
features = df.drop('Crop_Damage', axis = 1)
#create the train/test split
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.33, random_state=10)
#Create the model and train
model = RandomForestClassifier()
model.fit(X_train,y_train)
#predict the results for test
test_pred = model.predict(X_test)
#test the accuracy
accuracy_score(y_test, test_pred)

0.8360058309037901

In [811]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,:-1],df.iloc[:,-1],test_size=0.33,random_state=42)
KNC=KNeighborsClassifier(n_neighbors=26)
KNC.fit(x_train,y_train)
pred=KNC.predict(x_test)
acc_sc=accuracy_score(y_test,pred)
print("Accuracy score is",acc_sc)

Accuracy score is 0.8192419825072886


In [812]:
from sklearn.naive_bayes import MultinomialNB
mnb=MultinomialNB()
mnb.fit(x_train,y_train)
predmnb=mnb.predict(x_test)
print("accuracy score:",accuracy_score(y_test,predmnb))
print("confusion matrix:",confusion_matrix(y_test,predmnb))
print("classification report:",classification_report(y_test,predmnb))

accuracy score: 0.7733236151603499
confusion matrix: [[1004  128    4]
 [ 137   57    0]
 [  27   15    0]]
classification report:               precision    recall  f1-score   support

           0       0.86      0.88      0.87      1136
           1       0.28      0.29      0.29       194
           2       0.00      0.00      0.00        42

    accuracy                           0.77      1372
   macro avg       0.38      0.39      0.39      1372
weighted avg       0.75      0.77      0.76      1372



In [813]:
from sklearn.svm import SVC
svc=SVC(kernel='rbf')
svc.fit(x_train,y_train)
svc.score(x_train,y_train)
predsvc=svc.predict(x_test)
print("accuracy score:",accuracy_score(y_test,predsvc))
print("confusion matrix:",confusion_matrix(y_test,predsvc))
print("classification report:",classification_report(y_test,predsvc))

accuracy score: 0.8279883381924198
confusion matrix: [[1136    0    0]
 [ 194    0    0]
 [  42    0    0]]
classification report:               precision    recall  f1-score   support

           0       0.83      1.00      0.91      1136
           1       0.00      0.00      0.00       194
           2       0.00      0.00      0.00        42

    accuracy                           0.83      1372
   macro avg       0.28      0.33      0.30      1372
weighted avg       0.69      0.83      0.75      1372



C:\Users\mayraj\Documents\isha\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [814]:
dtc=DecisionTreeClassifier()
dtc.fit(x_train,y_train)
dtc.score(x_train,y_train)
preddtcc=dtc.predict(x_test)
print("accuracy score:",accuracy_score(y_test,preddtcc))
print("confusion matrix:",confusion_matrix(y_test,preddtcc))
print("classification report:",classification_report(y_test,preddtcc))

accuracy score: 0.7405247813411079
confusion matrix: [[961 152  23]
 [133  50  11]
 [ 27  10   5]]
classification report:               precision    recall  f1-score   support

           0       0.86      0.85      0.85      1136
           1       0.24      0.26      0.25       194
           2       0.13      0.12      0.12        42

    accuracy                           0.74      1372
   macro avg       0.41      0.41      0.41      1372
weighted avg       0.75      0.74      0.74      1372



In [815]:
knc=KNeighborsClassifier()
knc.fit(x_train,y_train)
knc.score(x_train,y_train)
predknc=knc.predict(x_test)
print("accuracy score:",accuracy_score(y_test,predknc))
print("conusion matrix:",confusion_matrix(y_test,predknc))
print("classification:",classification_report(y_test,predknc))

accuracy score: 0.8083090379008746
conusion matrix: [[1086   49    1]
 [ 171   23    0]
 [  36    6    0]]
classification:               precision    recall  f1-score   support

           0       0.84      0.96      0.89      1136
           1       0.29      0.12      0.17       194
           2       0.00      0.00      0.00        42

    accuracy                           0.81      1372
   macro avg       0.38      0.36      0.35      1372
weighted avg       0.74      0.81      0.76      1372



In [816]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(x_train,y_train)
gnb.score(x_train,y_train)
predgnb=gnb.predict(x_test)
print("accuracy score:",accuracy_score(y_test,predgnb))
print("conusion matrix:",confusion_matrix(y_test,predgnb))
print("classification report:",classification_report(y_test,predgnb))

accuracy score: 0.7908163265306123
conusion matrix: [[1039   97    0]
 [ 148   46    0]
 [  34    8    0]]
classification report:               precision    recall  f1-score   support

           0       0.85      0.91      0.88      1136
           1       0.30      0.24      0.27       194
           2       0.00      0.00      0.00        42

    accuracy                           0.79      1372
   macro avg       0.39      0.38      0.38      1372
weighted avg       0.75      0.79      0.77      1372



C:\Users\mayraj\Documents\isha\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [817]:
svc=SVC(kernel='poly')
svc.fit(x_train,y_train)
svc.score(x_train,y_train)
predsvc=svc.predict(x_test)
print("accuracy score:",accuracy_score(y_test,predsvc))
print("conusion matrix:",confusion_matrix(y_test,predsvc))
print("classification report:",classification_report(y_test,predsvc))

accuracy score: 0.8279883381924198
conusion matrix: [[1136    0    0]
 [ 194    0    0]
 [  42    0    0]]
classification report:               precision    recall  f1-score   support

           0       0.83      1.00      0.91      1136
           1       0.00      0.00      0.00       194
           2       0.00      0.00      0.00        42

    accuracy                           0.83      1372
   macro avg       0.28      0.33      0.30      1372
weighted avg       0.69      0.83      0.75      1372



C:\Users\mayraj\Documents\isha\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
df1=pd.DataFrame(predsvc)
df1.to_csv('sv_prediction.csv')

In [818]:
lg=LogisticRegression()

In [819]:
lg.fit(x_train,y_train)

C:\Users\mayraj\Documents\isha\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [820]:
pred=lg.predict(x_test)

In [821]:
print("accuracy score:",accuracy_score(y_test,pred))

accuracy score: 0.8185131195335277


In [786]:
print(confusion_matrix(y_test,pred))

[[1013   20    0]
 [ 166    9    0]
 [  38    2    0]]


In [787]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.83      0.98      0.90      1033
           1       0.29      0.05      0.09       175
           2       0.00      0.00      0.00        40

    accuracy                           0.82      1248
   macro avg       0.37      0.34      0.33      1248
weighted avg       0.73      0.82      0.76      1248



C:\Users\mayraj\Documents\isha\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [822]:
rd = RandomForestClassifier()
import joblib
joblib.dump(rd,'agri.pkl')

['agri.pkl']